[tool.poetry]
name = "ehroes"
version = "1.3.0"
description = "EHRoes: an all-in-one web application for patientsâ€™ data digitization and exploration"
authors = ["Corentin Meyer <co.meyer@unistra.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
pip = "*"
setuptools = "*"
wheel = "*"
scikit-learn = "^1"
scikit-image = "^0"
dash = "^2"
Flask = "^2"
Flask-WTF = "^0"
WTForms = "^2"
wtforms-validators = "^1"
Flask-Login = "^0"
Flask-SQLAlchemy = "^2"
Flask-Mail = "^0"
python-dotenv = "^0"
pandas = "^1.3"
numpy = "^1"
plotly = "^5"
CairoSVG = "^2"
Pillow = "^9"
joblib = "^1"
dash-core-components = "^2"
dash-bootstrap-components = "^1"
Flask-Migrate = "^3"
Flask-Session = "^0"
pytesseract = "^0"
pdf2image = "^1"
spacy = "^3"
thefuzz = "^0"
email-validator = "^1"
dash-html-components = "^2"
gunicorn = "^20"
opencv-python-headless = "^4"
python-Levenshtein = "^0.12.2"
PyJWT = "^2.3.0"
en_core_web_sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl" }
fr_core_news_sm = { url = "https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.2.0/fr_core_news_sm-3.2.0-py3-none-any.whl" }
Flask-Cors = "^3.0.10"

[tool.poetry.dev-dependencies]
black = {extras = ["jupyter"], version = "*"}
ipykernel = "^6"
pylint = "^2.11"
pylint-flask-sqlalchemy = "^0"
pylint-flask = "^0"
unittest2 = "^1"
pytest = "^6.2.5"
bandit = "^1.7.1"
pre-commit = "^2.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
